author:
  name: Maksim Babenko
  email: mbabenko21@gmail.com

app:
  name: "Likedimion-2"
  version: "0.0.1-dev"
  mode: "development"
  services_dir: "@RES_DIR/services"
  secret: "Consillieri Coding Team Forever"
  locale: "@RES_DIR/translations/ru_RU.yml"
  exp_table: "@RES_DIR/exp_table.yml"
  remember_days: 30
  exp_rate: 1
  base_delay: 2
  max_lvl: 99

new_player:
  #warrior
  1:
    str: 10
    dex: 5
    int: 2
    end: 10
    spr: 1
  2:
    str: 1
    dex: 5
    int: 10
    end: 2
    spr: 10
  3:
    str: 2
    dex: 10
    int: 6
    end: 7
    spr: 3

timers:
  crim: 1800

doctrine:
  db_params:
    driver: "pdo_mysql"
    user: "root"
    password: "qwerty"
    dbname: "likedimion"
  is_dev_mode: true
  entity_paths: ["@SRC_DIR/likedimion/lib/Likedimion/Database/Entity"]
  migrations: "@RES_DIR/doctrine/migrations"
  proxy_dir: "@RES_DIR/doctrine/proxy"
  proxy_namespace: "Likedimion\\Proxies"