#
parameters:
  account_service_class: "Likedimion\\Database\\Service\\AccountServiceImpl"
  player_service_class: "Likedimion\\Database\\Service\\PlayerServiceImpl"
  auth_service_class: "Likedimion\\Tools\\AuthServiceImpl"
  token_service_class: "Likedimion\\Database\\Service\\TokenServiceImpl"


  ####
  token_entity: "Likedimion\\Database\\Entity\\Token"
  account_entity: "Likedimion\\Database\\Entity\\Account"
  player_entity: "Likedimion\\Database\\Entity\\Player"

